### ISSUE TITLE
Reverse accessor clashes

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [yourlabs/django-cities-light#116]
Having imported everything as I oughta, I get the following:

```
ERRORS:
cities_light.City.country: (fields.E304) Reverse accessor for 'City.country' clashes with reverse accessor for 'City.country'.
    HINT: Add or change a related_name argument to the definition for 'City.country' or 'City.country'.
cities_light.City.region: (fields.E304) Reverse accessor for 'City.region' clashes with reverse accessor for 'City.region'.
    HINT: Add or change a related_name argument to the definition for 'City.region' or 'City.region'.
cities_light.Region.country: (fields.E304) Reverse accessor for 'Region.country' clashes with reverse accessor for 'Region.country'.
    HINT: Add or change a related_name argument to the definition for 'Region.country' or 'Region.country'.
pandion_api.City.country: (fields.E304) Reverse accessor for 'City.country' clashes with reverse accessor for 'City.country'.
    HINT: Add or change a related_name argument to the definition for 'City.country' or 'City.country'.
pandion_api.City.region: (fields.E304) Reverse accessor for 'City.region' clashes with reverse accessor for 'City.region'.
    HINT: Add or change a related_name argument to the definition for 'City.region' or 'City.region'.
pandion_api.Region.country: (fields.E304) Reverse accessor for 'Region.country' clashes with reverse accessor for 'Region.country'.
    HINT: Add or change a related_name argument to the definition for 'Region.country' or 'Region.country'.
```

Am I doing something wrong here?
